# Site
title:
bio:                'Manikanta Reddy D'
description:        ""
reading_time:       true
words_per_minute:   200
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                'http://localhost:4000'
logo:               'http://localhost:4000/assets/img/logo.png'
background:         'http://localhost:4000/assets/img/placeholder-big.jpg'

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   manikantareddyd

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              manikanta.reddy.d@outlook.com
twitter:            ManikantaReddyD
facebook:           Manikanta.D.Reddy
github:             ManikantaReddyD
stackoverflow:     6345500/manikanta-reddy-d
linkedin:          ManikantaDReddy
#xing:              username
#instagram:          username
lastfm:            ManikantaReddy
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
youtube:           UCnwMLnk0Z61kFt3igpCkrvQ
soundcloud:        ManikantaReddyD
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com

gist:
  noscript: false

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
